[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "scripts"

# Compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Formatting
line_length = 120
tab_width = 4
bracket_spacing = true

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 50 }

[profile.lite]
fuzz = { runs = 32 }
invariant = { runs = 32 }
optimizer = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
